CREATE FUNCTION [dbo].[SF_EncryptedPassword]
(
	@MotDePasse NVARCHAR(MAX),
	@salt CHAR(8)
)
RETURNS NVARCHAR(MAX)
AS
BEGIN
	RETURN HASHBYTES('SHA2_256',CONCAT(SUBSTRING(@salt,0,4),@MotDePasse,SUBSTRING(@salt,4,4)))
END
